name: CI Calculator Complete

on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

  # Tous ces jobs vont se lancer EN MÊME TEMPS
  Test_Add:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir build && cd build && cmake .. && make
          ./src/calculator add 10 5

  Test_Sub:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir build && cd build && cmake .. && make
          ./src/calculator sub 10 5

  Test_Mul:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir build && cd build && cmake .. && make
          ./src/calculator mul 10 5

  Test_Div:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir build && cd build && cmake .. && make
          ./src/calculator div 10 5

  Test_Car:
    needs: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir build && cd build && cmake .. && make
          ./src/calculator car 5

  # Ce job attend que TOUS les tests soient finis
  Deployment:
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy message
        run: echo "Déploiement de la solution en production"
